### ISSUE TITLE
I get diagnostics on `.node_modules` files

### ISSUE THREAD

**Issue by marcelmanz** [MunifTanjim/eslint.nvim#4]
I get diagnostics on the `node_modules` folder, and because the formatting, the screen gets full of inline red diagnostics. Like this: 

<img width="1540" alt="Screenshot 2022-11-14 at 12 54 36" src="https://user-images.githubusercontent.com/62728887/201653864-fbc659e7-9a65-4726-98df-2607938e5b0e.png">

this is my `eslint` config:
```lua
require("eslint").setup {
	bin = "eslint_d",
	code_actions = {
		enable = true,
		apply_on_save = {
			enable = true,
			types = { "problem" }, -- "directive", "problem", "suggestion", "layout"
		},
		disable_rule_comment = {
			enable = true,
			location = "separate_line", -- or `same_line`
		},
	},
	diagnostics = {
		enable = true,
		-- report_unused_disable_directives = false,
		run_on = "type", -- or `save`
	},
}
```

nvim version: `NVIM v0.9.0-dev-179+g5cf820f38-dirty`

**Comment by MunifTanjim** [comment]
Looks like your eslint config is not ignoring `node_modules`. It's unlikely to be related to this plugin.

And if you want to remove those virtual texts, check `:help vim.diagnostic.config()`.

**Comment by marcelmanz** [comment]
> Looks like your eslint config is not ignoring `node_modules`. It's unlikely to be related to this plugin.
> 
> And if you want to remove those virtual texts, check `:help vim.diagnostic.config()`.

It is strange because I think the `.eslintignore` that I am using should be enough:
```
**/*{.,-}min.js
**/node_modules/**/*
build
/**/*.d.ts
**/apps/dashboard/**
```

**Comment by marcelmanz** [comment]
seems that the config works with the `eslint` command:
<img width="716" alt="Screenshot 2022-11-14 at 14 32 19" src="https://user-images.githubusercontent.com/62728887/201672928-34569ed1-1991-4749-91e9-684fa33a03fe.png">

**Comment by MunifTanjim** [comment]
Whats the output when you run `eslint_d` instead of `eslint`? 🤔

**Comment by MunifTanjim** [comment]
I only get that single warning (just like your screenshot), if I open a file inside `node_modules`:

<img width="916" alt="image" src="https://user-images.githubusercontent.com/8050659/201685687-ac5c0f95-336e-4400-93aa-deea038c1067.png">

No other errors. I'm also using `eslint_d` with this plugin.

If you could provide a reproducible example, I can take a look. Otherwise I don't think I'll be able to help much.

**Comment by marcelmanz** [comment]
I will add an example.

**Comment by marcelmanz** [comment]
> Whats the output when you run `eslint_d` instead of `eslint`? 🤔

same result:
<img width="718" alt="Screenshot 2022-11-14 at 17 10 48" src="https://user-images.githubusercontent.com/62728887/201709009-b84fe5de-e323-45ae-bbd0-f8e621e584a8.png">

**Comment by MunifTanjim** [comment]
- How are you opening Neovim?
- What's the output of `:lua print(vim.loop.cwd())`?

**Comment by marcelmanz** [comment]
> How are you opening Neovim?

I open Neovim with the `neovim` command in the root of the repository. I used the full path of the files for testing the command because I copied the file path with `:!echo % | pbopy`


> What's the output of `:lua print(vim.loop.cwd())`?

`/Users/marcelmanzanares2/clones/work/stuart-frontend`

**Comment by MunifTanjim** [comment]
Well, everything sounds good 😂 That's how everything should be.

But I still can't reproduce it... so I have no idea how to fix it for your setup.

**Comment by marcelmanz** [comment]
Thanks anyway, I will try to find the cause.

**Comment by MunifTanjim** [comment]
You can try killing `eslint_d` process and install the latest version of `eslint_d`... just in case.

**Comment by marcelmanz** [comment]
I am using the latest: `v8.27.0 (eslint_d v12.2.1)`

**Comment by marcelmanz** [comment]
I am trying to patch this by using an autocommand.

This is the current config, but I don't know why it does not work:

```lua
local ag = vim.api.nvim_create_augroup
local au = vim.api.nvim_create_autocmd

local disable_node_modules_eslint_group = ag("DisableDiagnosticsNodeModules", { clear = true })

local disable_node_modules_eslint = function()
    print("disable_diagnostics_node_modules")
	vim.diagnostic.hide(nil, 0)
end

au({ "BufNewFile", "BufRead" }, {
	pattern = { "**/node_modules/**", "node_modules", "/node_modules/*" },
	callback = disable_node_modules_eslint,
	group = disable_node_modules_eslint_group,
})
```

if I run `:lua vim.diagnostic.hide(nil, 0)` it works perfectly. 
and the print inside `disable_node_modules_eslint` works too.

**Comment by marcelmanz** [comment]
Ok I "fixed" it using `vim.wait`, works 50% of the cases haha:

```lua
local disable_node_modules_eslint = function(bufnr)
	vim.wait(100,function()
		vim.diagnostic.hide(nil, bufnr.id)
	end, 100)
end
```

**Comment by marcelmanz** [comment]
@MunifTanjim is there any news with this error or the auto commands that I explain above? Thanks in advance.

**Comment by MunifTanjim** [comment]
I'm still using the plugin daily. So far haven't been able to reproduce the issue 😅

For now, your best bet would be to use the built-in eslint integration that comes with [`null-ls`](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md) or a the dedicated eslint server integration that comes with [`nvim-lspconfig`](https://github.com/neovim/nvim-lspconfig/blob/0687eaacc634a82f4832599653ad1305fdf0c941/lua/lspconfig/server_configurations/eslint.lua) (I think you can install it with `:MasonInstall eslint-lsp` if you're using mason.nvim).

**Comment by marcelmanz** [comment]
The `nvim-lspconfig` for ESLint has the same problem, with the only difference that the autocommand now works properly. 🤷🏽 

This is my final config:

`lua/lsp/eslint.lua`:
```lua
require("lspconfig").eslint.setup {
	codeAction = {
		disableRuleComment = {
			enable = true,
			location = "separateLine",
		},
		showDocumentation = {
			enable = true,
		},
	},
	codeActionOnSave = {
		enable = false,
		mode = "all",
	},
	experimental = {
		useFlatConfig = false,
	},
	format = true,
	nodePath = "",
	onIgnoredFiles = "off",
	packageManager = "npm",
	problems = {
		shortenToSingleLine = false,
	},
	quiet = false,
	rulesCustomizations = {},
	run = "onType",
	useESLintClass = false,
	validate = "on",
	workingDirectory = {
		mode = "location",
	},
}
```

`/lua/autocommands.lua`:
```lua
local ag = vim.api.nvim_create_augroup
local au = vim.api.nvim_create_autocmd

-- GROUPS:
local disable_node_modules_eslint_group =
	ag("DisableNodeModulesEslint", { clear = true })

-- AUTO-COMMANDS:
au({ "BufNewFile", "BufRead" }, {
	pattern = { "**/node_modules/**", "node_modules", "/node_modules/*" },
	callback = function()
		vim.diagnostic.disable(0)
	end,
	group = disable_node_modules_eslint_group,
})
```
