### ISSUE TITLE
Any way of using with `.eslintrc.js`?

### ISSUE THREAD

**Issue by igorcafe** [MunifTanjim/eslint.nvim#5]
for me it is basically using a eslint default config, but i have many projects with different rules and I wish there is a way to load config from .eslintrc.js

**Comment by MunifTanjim** [comment]
If you have eslint config, it should automatically be using that config. No need to load anything manually, just open Neovim in your project directory (where the eslint config is).

**Comment by marcelmanz** [comment]
this happens to me too with `.eslinrc.json`, it formats with other config, but the diagnostics are using the root config
